version: "3.9"

volumes: 
  dbdata:
  code:

services: 
  webserver:
    container_name: webserver
    build: webserver
    ports: 
      - 80:80
    volumes: 
      - code:/var/www/html
      - ./webserver/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
  database:
    image: mariadb:latest
    container_name: mariadb
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - dbdata:/var/lib/mysql
      - 2021sportverein.sql