version: "3.9"

volumes:
  dbdata:

services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    build: ../backend
    volumes:
      - ../backend:/var/www/html/
    ports:
      - "80:80"

  angular-service:
    container_name: angular-app
    build: ../frontend/ng-webbased-database-manager-ui
    volumes:
      - ../frontend/ng-webbased-database-manager-ui:/usr/src/app

    ports:
      - '4200:4200'
    command: /usr/src/app/entrypoint.sh
   

  mysql:
    container_name: mariadb
    image: mariadb:10.3
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
