version: "3.9"

volumes:
  dbdata:

services:
  webserver:
    container_name: webserver
    build: webserver
    ports:
      - 80:80
    volumes:
      - ../backend/src:/var/www/html/
  mysql:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
