version: "3.9"

volumes: 
  dbdata:
  code:

services: 
  webserver:
    container_name: webserver
    build: webserver
    ports: 
      - 80:80
    volumes: 
      - code:/var/www/html
      - ./webserver/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
  mysql:
    image: mariadb:10.3
    container_name: mariadb
    volumes:
      - dbdata:/var/lib/mysql
      - ./2021sportverein.sql:/docker-entrypoint-initdb.d/2021sportverein.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"